<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
| If this is not set then CodeIgniter will guess the protocol, domain and
| path to your installation.
|
*/
$config['base_url']	= 'http://www.propertyfinder.com';

/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = '';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'AUTO' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'AUTO'			Default - auto detects
| 'PATH_INFO'		Uses the PATH_INFO
| 'QUERY_STRING'	Uses the QUERY_STRING
| 'REQUEST_URI'		Uses the REQUEST_URI
| 'ORIG_PATH_INFO'	Uses the ORIG_PATH_INFO
|
*/
$config['uri_protocol']	= 'AUTO';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/urls.html
*/

$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = FALSE;


/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/core_classes.html
| http://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';


/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify with a regular expression which characters are permitted
| within your URLs.  When someone tries to submit a URL with disallowed
| characters they will get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';


/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['allow_get_array']		= TRUE;
$config['enable_query_strings'] = FALSE;
$config['controller_trigger']	= 'c';
$config['function_trigger']		= 'm';
$config['directory_trigger']	= 'd'; // experimental not currently in use

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| If you have enabled error logging, you can set an error threshold to
| determine what gets logged. Threshold options are:
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 0;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ folder. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| system/cache/ folder.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class or the Session class you
| MUST set an encryption key.  See the user guide for info.
|
*/
$config['encryption_key'] = '';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_cookie_name'		= the name you want for the cookie
| 'sess_expiration'			= the number of SECONDS you want the session to last.
|   by default sessions last 7200 seconds (two hours).  Set to zero for no expiration.
| 'sess_expire_on_close'	= Whether to cause the session to expire automatically
|   when the browser window is closed
| 'sess_encrypt_cookie'		= Whether to encrypt the cookie
| 'sess_use_database'		= Whether to save the session data to a database
| 'sess_table_name'			= The name of the session database table
| 'sess_match_ip'			= Whether to match the user's IP address when reading the session data
| 'sess_match_useragent'	= Whether to match the User Agent when reading the session data
| 'sess_time_to_update'		= how many seconds between CI refreshing Session Information
|
*/
$config['sess_cookie_name']		= 'ci_session';
$config['sess_expiration']		= 7200;
$config['sess_expire_on_close']	= TRUE;
$config['sess_encrypt_cookie']	= TRUE;
$config['sess_use_database']	= FALSE;
$config['sess_table_name']		= 'ci_sessions';
$config['sess_match_ip']		= FALSE;
$config['sess_match_useragent']	= TRUE;
$config['sess_time_to_update']	= 300;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix' = Set a prefix if you need to avoid collisions
| 'cookie_domain' = Set to .your-domain.com for site-wide cookies
| 'cookie_path'   =  Typically will be a forward slash
| 'cookie_secure' =  Cookies will only be set if a secure HTTPS connection exists.
|
*/
$config['cookie_prefix']	= "STLR";
$config['cookie_domain']	= "";
$config['cookie_path']		= "/";
$config['cookie_secure']	= FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
*/
$config['csrf_protection'] = FALSE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or 'gmt'.  This pref tells the system whether to use
| your server's local time as the master 'now' reference, or convert it to
| GMT.  See the 'date helper' page of the user guide for information
| regarding date handling.
|
*/
$config['time_reference'] = 'local';


/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
*/
$config['rewrite_short_tags'] = FALSE;


/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy IP
| addresses from which CodeIgniter should trust the HTTP_X_FORWARDED_FOR
| header in order to properly identify the visitor's IP address.
| Comma-delimited, e.g. '10.0.1.200,10.0.1.201'
|
*/
$config['proxy_ips'] = '';


/*
|--------------------------------------------------------------------------
| SMTP/Email
|--------------------------------------------------------------------------
|
*/
$config['smtp_host']	= "";
$config['smtp_port']	= "";
$config['smtp_user']	= "";
$config['smtp_pass']	= "";

$config['email_from_register']	= "";
$config['email_from_name_register']	= "";
$config['email_subject_register']	= "";

$config['email_to_contactus']	= "";
$config['email_to_name_contactus']	= "";
$config['email_subject_contactus']	= "";

$config['email_from_forgotpassword']	= "";
$config['email_from_name_forgotpassword']	= "";
$config['email_subject_forgotpassword']	= "";

$config['email_from_invoice']	= "";
$config['email_from_name_invoice']	= "";
$config['email_subject_invoice']	= "";


/*
|--------------------------------------------------------------------------
| SMTP/Email
|--------------------------------------------------------------------------
|
*/
$config['paymentmode']    = 'paypal'; //paypal, sandbox
$config['paypal_businessemail']    = 'business2@propertygusto.com';
$config['paypal_return']  = "payment/complete";
$config['paypal_cancel']  = "payment/cancel";
$config['paypal_notifyurl']  = "payment/process";
$config['paypal_currency'] = 'SGD';
$config['paypal_country'] = 'SG';


/*
|--------------------------------------------------------------------------
| List of facilities
|--------------------------------------------------------------------------
|
*/
$config['image_path'] = '../../assets/img/';


/*
|--------------------------------------------------------------------------
| List of facilities
|--------------------------------------------------------------------------
|
*/

//Residential
$config['facilities_residentials'] = array(
    '24S' => '24 Hour Security',
    'ADVP' => 'Adventure Park',
    'AER' => 'Aerobic Pool',
    'AMPI' => 'Ampitheater',
    'BAD' => 'Badminton Hall',
    'BCP' => 'Basement Car Park',
    'BC' => 'Basketball Court',
    'BBQ' => 'BBQ Pits',
    'BLRD' => 'Billiards Room',
    'BOWL' => 'Bowling Alley',
    'CPK' => 'Car Parking',
    'CLF' => 'Cargo Lift',
    'CCTV' => 'CCTV',
    'CLB' => 'Clubhouse',
    'DRV' => 'Driving Range',
    'ELEC' => 'Electric Generator',
    'FIT' => 'Fitness Corner',
    'FUN' => 'Fun Pool',
    'FNC' => 'Function Room',
    'GME' => 'Game Room',
    'GRD' => 'Guard House',
    'GYM' => 'Gym',
    'JAC' => 'Jacuzzi',
    'JOG' => 'Jogging Track',
    'KRK' => 'Karaoke',
    'LAP' => 'Lap Pool',
    'LDY' => 'Launderette',
    'LBY' => 'Library',
    'LOAD' => 'Loading Bay',
    'LOB' => 'Lobby',
    'LOU' => 'Lounge',
    'ML' => 'Mail Box',
    'GLF' => 'Mini Golf Range',
    'MRT' => 'Mini-Mart',
    'HALL' => 'Multi-Purpose Hall',
    'PNY' => 'Pantry',
    'PARK' => 'Park/Garden',
    'PAV' => 'Pavillion',
    'PLAY' => 'Playground',
    'POOL' => 'Pool Deck',
    'RCP' => 'Reception',
    'RFX' => 'Reflexology Path',
    'SAU' => 'Sauna',
    'SKY' => 'Sky Lounge',
    'SPA' => 'Spa Pool',
    'SQC' => 'Squash Court',
    'STB' => 'Steam Bath',
    'SWM' => 'Swimming Pool',
    'TEN' => 'Tennis Courts',
    'WAD' => 'Wading Pool',
    'WP' => 'Water Pump'
);
//Residential
$config['facilities_commercials'] = array(
    '24S' => '24 Hour Security',
    'BCP' => 'Basement Car Park',
    'CPK' => 'Car Parking',
    'CLF' => 'Cargo Lift',
    'CCTV' => 'CCTV',
    'CONF' => 'Conference Rooms',
    'ELEC' => 'Electric Generator',
    'FNC' => 'Function Room',
    'GME' => 'Game Room',
    'GRD' => 'Guard House',
    'GYM' => 'Gym',
    'LBY' => 'Library',
    'LOAD' => 'Loading Bay',
    'LOB' => 'Lobby',
    'LOU' => 'Lounge',
    'ML' => 'Mail Box',
    'MEET' => 'Meeting Room',
    'HALL' => 'Multi-Purpose Hall',
    'PNY' => 'Pantry',
    'PARK' => 'Park/Garden',
    'PAV' => 'Pavillion',
    'RCP' => 'Reception',
    'SRV' => 'Server Room',
    'WP' => 'Water Pump'
);
//Land
$config['facilities_lands'] = array(
);
//Hotels/Resorts
$config['facilities_hotels'] = array(
    '24S' => '26 Hour Security',
    'ADVP' => 'Adventure Park',
    'AER' => 'Aerobic Pool',
    'AMPI' => 'Ampitheater',
    'BAD' => 'Badminton Hall',
    'BCP' => 'Basement Car Park',
    'BC' => 'Basketball Court',
    'BBQ' => 'BBQ Pits',
    'BLRD' => 'Billiards Room',
    'BOWL' => 'Bowling Alley',
    'CPK' => 'Car Parking',
    'CLF' => 'Cargo Lift',
    'CCTV' => 'CCTV',
    'CLB' => 'Clubhouse',
    'CONF' => 'Conference Rooms',
    'DRV' => 'Driving Range',
    'ELEC' => 'Electric Generator',
    'FIT' => 'Fitness Corner',
    'FUN' => 'Fun Pool',
    'FNC' => 'Function Room',
    'GME' => 'Game Room',
    'GRD' => 'Guard House',
    'GYM' => 'Gym',
    'JAC' => 'Jacuzzi',
    'JOG' => 'Jogging Track',
    'KRK' => 'Karaoke',
    'LAP' => 'Lap Pool',
    'LDY' => 'Launderette',
    'LBY' => 'Library',
    'LOAD' => 'Loading Bay',
    'LOB' => 'Lobby',
    'LOU' => 'Lounge',
    'ML' => 'Mail Box',
    'MEET' => 'Meeting Room',
    'GLF' => 'Mini Golf Range',
    'MRT' => 'Mini-Mart',
    'HALL' => 'Multi-Purpose Hall',
    'PARK' => 'Park/Garden',
    'PAV' => 'Pavillion',
    'PLAY' => 'Playground',
    'POOL' => 'Pool Deck',
    'RCP' => 'Reception',
    'RFX' => 'Reflexology Path',
    'SAU' => 'Sauna',
    'SKY' => 'Sky Lounge',
    'SPA' => 'Spa Pool',
    'SQC' => 'Squash Court',
    'STB' => 'Steam Bath',
    'SWM' => 'Swimming Pool',
    'TEN' => 'Tennis Courts',
    'WAD' => 'Wading Pool',
    'WP' => 'Water Pump'
);


/*
|--------------------------------------------------------------------------
| List of features
|--------------------------------------------------------------------------
|
*/

//Residential
$config['features_residentials'] = array(
    'END' => 'Corner/End Unit',
    'SEA' => 'Sea View',
    'CTY' => 'City View',
    'PRK' => 'Park / Greenery View',
    'SWM' => 'Swimming Pool View',
    'GF' => 'Ground Floor',
    'LF' => 'Low Floor',
    'HF' => 'High Floor',
    'NEW' => 'Brand New',
    'ORG' => 'Original Condition',
    'REN' => 'Renovated'
);
//Commercial
$config['features_commercials'] = array(
    'END' => 'Corner/End Unit',
    'SEA' => 'Sea View',
    'CTY' => 'City View',
    'PRK' => 'Park / Greenery View',
    'SWM' => 'Swimming Pool View',
    'GF' => 'Ground Floor',
    'LF' => 'Low Floor',
    'HF' => 'High Floor',
    'NEW' => 'Brand New',
    'ORG' => 'Original Condition',
    'REN' => 'Renovated'
);
//Land
$config['features_lands'] = array(
    'SEA' => 'Sea View',
    'CTY' => 'City View',
    'PRK' => 'Park / Greenery View',
    'RES' => 'Residential Area',
    'COM' => 'Commercial Area'
);
//Hotels/Resorts
$config['features_hotels'] = array(
    'END' => 'Corner/End Unit',
    'SEA' => 'Sea View',
    'CTY' => 'City View',
    'PRK' => 'Park / Greenery View',
    'SWM' => 'Swimming Pool View',
    'GF' => 'Ground Floor',
    'LF' => 'Low Floor',
    'HF' => 'High Floor',
    'NEW' => 'Brand New',
    'ORG' => 'Original Condition',
    'REN' => 'Renovated'
);


/*
|--------------------------------------------------------------------------
| List of furnishings
|--------------------------------------------------------------------------
|
*/

//Residential
$config['furnishings_residentials'] = array(
    'AC' => 'Air Conditioning',
    'BTH' => 'Bathtub',
    'BED' => 'Beds',
    'CTV' => 'Cable TV-ready',
    'HOOD' => 'Cooker Hood',
    'DINE' => 'Dining Furnitures',
    'DB' => 'Door Bell',
    'DRS' => 'Dressers',
    'FP' => 'Fire Place',
    'FR' => 'Fridge',
    'GC' => 'Garbage Chute',
    'HT' => 'Heater',
    'HCS' => 'Hot/Cold Shower',
    'IC' => 'Intercom',
    'NET' => 'Internet Cables',
    'JAC' => 'Jacuzzi',
    'KC' => 'Kitchen Cabinets',
    'LRF' => 'Living Room Furnitures',
    'PC' => 'Phone Cables',
    'PP' => 'Private Pool',
    'TV' => 'TV',
    'WRD' => 'Wardrobes',
    'WH' => 'Water Heater'
);
//Commercial
$config['furnishings_commercials'] = array(
    'AC' => 'Air Conditioning',
    'CTV' => 'Cable TV-ready',
    'DB' => 'Door Bell',
    'FR' => 'Fridge',
    'GC' => 'Garbage Chute',
    'HT' => 'Heater',
    'IC' => 'Intercom',
    'NET' => 'Internet Cables',
    'LCK' => 'Lockers',
    'OC' => 'Office Chairs',
    'OT' => 'Office Tables',
    'PC' => 'Phone Cables',
    'TV' => 'TV',
    'WH' => 'Water Heater'
);
//Land
$config['furnishings_lands'] = array(
);
//Hotels/Resorts
$config['furnishings_hotels'] = array(
    'AC' => 'Air Conditioning',
    'BTH' => 'Bathtub',
    'BED' => 'Beds',
    'CTV' => 'Cable TV-ready',
    'HOOD' => 'Cooker Hood',
    'CCH' => 'Couch',
    'DINE' => 'Dining Furnitures',
    'DB' => 'Door Bell',
    'DRS' => 'Dressers',
    'FP' => 'Fire Place',
    'FR' => 'Fridge',
    'GC' => 'Garbage Chute',
    'HT' => 'Heater',
    'HCS' => 'Hot/Cold Shower',
    'IC' => 'Intercom',
    'NET' => 'Internet Cables',
    'JAC' => 'Jacuzzi',
    'PC' => 'Phone Cables',
    'PP' => 'Private Pool',
    'TV' => 'TV',
    'WRD' => 'Wardrobes',
    'WH' => 'Water Heater'
);


/*
|--------------------------------------------------------------------------
| List of countries
|--------------------------------------------------------------------------
|
*/

$config['countries'] = array(
    'MY' => 'Malaysia',
    'PH' => 'Philippines',
    'SG' => 'Singapore',
    'US' => 'United States',
    'AF' => 'Afghanistan',
    'AL' => 'Albania',
    'DZ' => 'Algeria',
    'AS' => 'American Samoa',
    'AD' => 'Andorra',
    'AO' => 'Angola',
    'AI' => 'Anguilla',
    'AQ' => 'Antarctica',
    'AG' => 'Antigua & Barbuda',
    'AR' => 'Argentina',
    'AM' => 'Armenia',
    'AW' => 'Aruba',
    'AU' => 'Australia',
    'AT' => 'Austria',
    'AZ' => 'Azerbaijan',
    'BS' => 'Bahamas',
    'BH' => 'Bahrain',
    'BD' => 'Bangladesh',
    'BB' => 'Barbados',
    'BY' => 'Belarus',
    'BE' => 'Belgium',
    'BZ' => 'Belize',
    'BJ' => 'Benin',
    'BM' => 'Bermuda',
    'BT' => 'Bhutan',
    'BO' => 'Bolivia',
    'BA' => 'Bosnia and Herzegovina',
    'BW' => 'Botswana',
    'BV' => 'Bouvet Island',
    'BR' => 'Brazil',
    'IO' => 'British Indian Ocean T.',
    'VG' => 'British Virgin Islands',
    'BN' => 'Brunei Darussalam',
    'BG' => 'Bulgaria',
    'BF' => 'Burkina Faso',
    'BI' => 'Burundi',
    'KH' => 'Cambodia',
    'CM' => 'Cameroon',
    'CA' => 'Canada',
    'CV' => 'Cape Verde',
    'KY' => 'Cayman Islands',
    'CF' => 'Central African Republic',
    'TD' => 'Chad',
    'CL' => 'Chile',
    'CN' => 'China',
    'CX' => 'Christmas Island',
    'CC' => 'Cocos (Keeling) Islands',
    'CO' => 'Colombia',
    'KM' => 'Comoros',
    'CG' => 'Congo',
    'CD' => 'Congo, Dem. Rep. of the',
    'CK' => 'Cook Islands',
    'CR' => 'Costa Rica',
    'HR' => 'Croatia',
    'CU' => 'Cuba',
    'CY' => 'Cyprus',
    'CZ' => 'Czech Republic',
    'DK' => 'Denmark',
    'DJ' => 'Djibouti',
    'DM' => 'Dominica',
    'DO' => 'Dominican Republic',
    'TP' => 'East Timor (Timor-Leste)',
    'EC' => 'Ecuador',
    'EG' => 'Egypt',
    'SV' => 'El Salvador',
    'GQ' => 'Equatorial Guinea',
    'ER' => 'Eritrea',
    'EE' => 'Estonia',
    'ET' => 'Ethiopia',
    'FK' => 'Falkland Islands (Malvinas)',
    'FO' => 'Faroe Islands',
    'FJ' => 'Fiji',
    'FI' => 'Finland',
    'FR' => 'France',
    'GF' => 'French Guiana',
    'PF' => 'French Polynesia',
    'TF' => 'French Southern Territory',
    'GA' => 'Gabon',
    'GM' => 'Gambia, the',
    'GE' => 'Georgia',
    'DE' => 'Germany',
    'GH' => 'Ghana',
    'GI' => 'Gibraltar',
    'GR' => 'Greece',
    'GL' => 'Greenland',
    'GD' => 'Grenada',
    'GP' => 'Guadeloupe',
    'GU' => 'Guam',
    'GT' => 'Guatemala',
    'GG' => 'Guernsey and Alderney',
    'GF' => 'Guiana, French',
    'GN' => 'Guinea',
    'GW' => 'Guinea-Bissau',
    'GP' => 'Guinea, Equatorial',
    'GY' => 'Guyana',
    'HT' => 'Haiti',
    'HM' => 'Heard & McDonald Is.(AU)',
    'HN' => 'Honduras',
    'HK' => 'Hong Kong',
    'HU' => 'Hungary',
    'IS' => 'Iceland',
    'IN' => 'India',
    'ID' => 'Indonesia',
    'IR' => 'Iran, Islamic Republic of',
    'IQ' => 'Iraq',
    'IE' => 'Ireland',
    'IL' => 'Israel',
    'IT' => 'Italy',
    'CI' => 'Ivory Coast (Cote d\'Ivoire)',
    'JM' => 'Jamaica',
    'JP' => 'Japan',
    'JE' => 'Jersey',
    'JO' => 'Jordan',
    'KZ' => 'Kazakhstan',
    'KE' => 'Kenya',
    'KI' => 'Kiribati',
    'KP' => 'Korea Dem. People\'s Rep.',
    'KR' => 'Korea, (South) Republic of',
    'KV' => 'Kosovo',
    'KW' => 'Kuwait',
    'KG' => 'Kyrgyzstan',
    'LA' => 'Laos',
    'LV' => 'Latvia',
    'LB' => 'Lebanon',
    'LS' => 'Lesotho',
    'LR' => 'Liberia',
    'LY' => 'Libyan Arab Jamahiriya',
    'LI' => 'Liechtenstein',
    'LT' => 'Lithuania',
    'LU' => 'Luxembourg',
    'MK' => 'Macedonia, TFYR',
    'MG' => 'Madagascar',
    'MW' => 'Malawi',
    'MV' => 'Maldives',
    'ML' => 'Mali',
    'MT' => 'Malta',
    'MH' => 'Marshall Islands',
    'MQ' => 'Martinique',
    'MR' => 'Mauritania',
    'MU' => 'Mauritius',
    'YT' => 'Mayotte',
    'MX' => 'Mexico',
    'FM' => 'Micronesia',
    'MD' => 'Moldova',
    'MC' => 'Monaco',
    'MN' => 'Mongolia',
    'CS' => 'Montenegro',
    'MS' => 'Montserrat',
    'MA' => 'Morocco',
    'MZ' => 'Mozambique',
    'MM' => 'Myanmar',
    'NA' => 'Namibia',
    'NR' => 'Nauru',
    'NP' => 'Nepal',
    'NL' => 'Netherlands',
    'NC' => 'New Caledonia',
    'NZ' => 'New Zealand',
    'NI' => 'Nicaragua',
    'NE' => 'Niger',
    'NG' => 'Nigeria',
    'NU' => 'Niue',
    'NF' => 'Norfolk Island',
    'MP' => 'Northern Mariana Islands',
    'NO' => 'Norway',
    'OM' => 'Oman',
    'PK' => 'Pakistan',
    'PW' => 'Palau',
    'PS' => 'Palestinian Territory',
    'PA' => 'Panama',
    'PG' => 'Papua New Guinea',
    'PY' => 'Paraguay',
    'PE' => 'Peru',
    'PN' => 'Pitcairn Island',
    'PL' => 'Poland',
    'PT' => 'Portugal',
    'PR' => 'Puerto Rico',
    'QA' => 'Qatar',
    'RO' => 'Romania',
    'RU' => 'Russia',
    'RW' => 'Rwanda',
    'EH' => 'Sahara, Western',
    'BL' => 'Saint Barthelemy',
    'SH' => 'Saint Helena',
    'KN' => 'Saint Kitts and Nevis',
    'LC' => 'Saint Lucia',
    'MF' => 'Saint Martin',
    'PM' => 'S Pierre & Miquelon',
    'VC' => 'S Vincent & Grenadines',
    'WS' => 'Samoa',
    'SM' => 'San Marino',
    'ST' => 'Sao Tome and Principe',
    'SA' => 'Saudi Arabia',
    'SN' => 'Senegal',
    'RS' => 'Serbia',
    'SC' => 'Seychelles',
    'SL' => 'Sierra Leone',
    'SK' => 'Slovakia',
    'SI' => 'Slovenia',
    'SB' => 'Solomon Islands',
    'SO' => 'Somalia',
    'ZA' => 'South Africa',
    'GS' => 'S.George & S.Sandwich',
    'SS' => 'South Sudan',
    'ES' => 'Spain',
    'LK' => 'Sri Lanka',
    'SD' => 'Sudan',
    'SR' => 'Suriname',
    'SJ' => 'Svalbard & Jan Mayen Is.',
    'SZ' => 'Swaziland',
    'SE' => 'Sweden',
    'CH' => 'Switzerland',
    'SY' => 'Syrian Arab Republic',
    'TW' => 'Taiwan',
    'TJ' => 'Tajikistan',
    'TZ' => 'Tanzania',
    'TH' => 'Thailand',
    'TL' => 'Timor-Leste (East Timor)',
    'TG' => 'Togo',
    'TK' => 'Tokelau',
    'TO' => 'Tonga',
    'TT' => 'Trinidad & Tobago',
    'TN' => 'Tunisia',
    'TR' => 'Turkey',
    'TM' => 'Turkmenistan',
    'TC' => 'Turks and Caicos Is.',
    'TV' => 'Tuvalu',
    'UG' => 'Uganda',
    'UA' => 'Ukraine',
    'AE' => 'United Arab Emirates',
    'UK' => 'United Kingdom',
    'UM' => 'US Minor Outlying Isl.',
    'UY' => 'Uruguay',
    'UZ' => 'Uzbekistan',
    'VU' => 'Vanuatu',
    'VA' => 'Vatican',
    'VE' => 'Venezuela',
    'VN' => 'Viet Nam',
    'VG' => 'Virgin Islands, British',
    'VI' => 'Virgin Islands, U.S.',
    'WF' => 'Wallis and Futuna',
    'EH' => 'Western Sahara',
    'YE' => 'Yemen',
    'ZM' => 'Zambia',
    'ZW' => 'Zimbabwe'
);


/*
|--------------------------------------------------------------------------
| List of currencies
|--------------------------------------------------------------------------
|
*/

$config['currencies'] = array(
    'PHP' => '₱',
    'USD' => '$',
    'SGD' => '$',
    'EUR' => '€',
    'GBP' => '£',
    'XAF' => 'Fr',
    'AED' => 'د.إ',
    'AFN' => '؋',
    'ALL' => 'L',
    'AMD' => 'դր.',
    'ANG' => 'ƒ',
    'AOA' => 'Kz',
    'ARS' => '$',
    'AUD' => '$',
    'AWG' => 'ƒ',
    'AZN' => '',
    'BAM' => 'KM or КМ',
    'BBD' => '$',
    'BDT' => '৳',
    'BGN' => 'лв',
    'BHD' => '.د.ب',
    'BIF' => 'Fr',
    'BMD' => '$',
    'BND' => '$',
    'BOB' => 'Bs.',
    'BRL' => 'R$',
    'BSD' => '$',
    'BTN' => 'Nu.',
    'BWP' => 'P',
    'BYR' => 'Br',
    'BZD' => '$',
    'CAD' => '$',
    'CDF' => 'Fr',
    'CHF' => 'Fr',
    'CLP' => '$',
    'CNY' => '¥',
    'COP' => '$',
    'CRC' => '₡',
    'CUC' => '$',
    'CUP' => '$',
    'CVE' => '$',
    'CZK' => 'Kč',
    'DJF' => 'Fr',
    'DKK' => 'kr',
    'DOP' => '$',
    'DZD' => 'د.ج',
    'EGP' => '£',
    'ERN' => 'Nfk',
    'ETB' => 'Br',
    'FJD' => '$',
    'FKP' => '£',
    'GEL' => 'ლ',
    'GGP' => '£',
    'GHS' => '₵',
    'GIP' => '£',
    'GMD' => 'D',
    'GNF' => 'Fr',
    'GTQ' => 'Q',
    'GYD' => '$',
    'HKD' => '$',
    'HNL' => 'L',
    'HRK' => 'kn',
    'HTG' => 'G',
    'HUF' => 'Ft',
    'IDR' => 'Rp',
    'ILS' => '₪',
    'IMP' => '£',
    'INR' => '',
    'IQD' => 'ع.د',
    'IRR' => '﷼',
    'ISK' => 'kr',
    'JEP' => '£',
    'JMD' => '$',
    'JOD' => 'د.ا',
    'JPY' => '¥',
    'KES' => 'Sh',
    'KGS' => 'лв',
    'KHR' => '៛',
    'KMF' => 'Fr',
    'KPW' => '₩',
    'KRW' => '₩',
    'KWD' => 'د.ك',
    'KYD' => '$',
    'KZT' => '₸',
    'LAK' => '₭',
    'LBP' => 'ل.ل',
    'LKR' => 'Rs',
    'LRD' => '$',
    'LSL' => 'L',
    'LTL' => 'Lt',
    'LVL' => 'Ls',
    'LYD' => 'ل.د',
    'MAD' => 'د.م.',
    'MDL' => 'L',
    'MGA' => 'Ar',
    'MKD' => 'ден',
    'MMK' => 'Ks',
    'MNT' => '₮',
    'MOP' => 'P',
    'MRO' => 'UM',
    'MUR' => '₨',
    'MVR' => '.ރ',
    'MWK' => 'MK',
    'MXN' => '$',
    'MYR' => 'RM',
    'MZN' => 'MT',
    'NAD' => '$',
    'NGN' => '₦',
    'NIO' => 'C$',
    'NOK' => 'kr',
    'NPR' => '₨',
    'NZD' => '$',
    'OMR' => 'ر.ع.',
    'PAB' => 'B/.',
    'PEN' => 'S/.',
    'PGK' => 'K',
    'PKR' => '₨',
    'PLN' => 'zł',
    'PRB' => 'р.',
    'PYG' => '₲',
    'QAR' => 'ر.ق',
    'RON' => 'L',
    'RSD' => 'дин.',
    'RUB' => 'р.',
    'RWF' => 'Fr',
    'SAR' => 'ر.س',
    'SBD' => '$',
    'SCR' => '₨',
    'SDG' => '£',
    'SEK' => 'kr',
    'SHP' => '£',
    'SLL' => 'Le',
    'SOS' => 'Sh',
    'SRD' => '$',
    'SSP' => '£',
    'STD' => 'Db',
    'SVC' => '₡',
    'SYP' => '£',
    'SZL' => 'L',
    'THB' => '฿',
    'TJS' => 'ЅМ',
    'TMT' => 'm',
    'TND' => 'د.ت',
    'TOP' => 'T$',
    'TRY' => '',
    'TTD' => '$',
    'TWD' => '$',
    'TZS' => 'Sh',
    'UAH' => '₴',
    'UGX' => 'Sh',
    'UYU' => '$',
    'UZS' => 'лв',
    'VEF' => 'Bs F',
    'VND' => '₫',
    'VUV' => 'Vt',
    'WST' => 'T',
    'XCD' => '$',
    'XOF' => 'Fr',
    'XPF' => 'Fr',
    'YER' => '﷼',
    'ZAR' => 'R',
    'ZMW' => 'ZK',
    'ZWL' => '$'
);


/* End of file config.php */
/* Location: ./application/config/config.php */